sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - 12
  - 11
  - 10
before_install:
  - npm i -g npm@^6.0.0
install:
  - npm install
before_script:
  - npm prune

script:
  - npm run lint
  - npm test
  - npm run check-coverage
  - npm run report-coverage
  - npm run build:prod

stages:
  - name: release
    if: branch = master

jobs:
  include:
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
